// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1npevTIB-cWUHSnN0RoMLmum9KjigLM',
    appId: '1:733116299116:web:13b33370e97346b98ae549',
    messagingSenderId: '733116299116',
    projectId: 'chat-e8237',
    authDomain: 'chat-e8237.firebaseapp.com',
    databaseURL: 'https://chat-e8237-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e8237.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKrd3wPXLu-yj6a92Hw2zl-lawYBnAuU',
    appId: '1:733116299116:android:94248927ca3dbc8f8ae549',
    messagingSenderId: '733116299116',
    projectId: 'chat-e8237',
    databaseURL: 'https://chat-e8237-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-e8237.appspot.com',
  );
}
